# Generated by Django 4.2 on 2023-11-12 10:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_loginpage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Registrationpage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=25)),
                ('surname', models.CharField(max_length=25)),
                ('mobile_or_email', models.CharField(max_length=100, validators=[django.core.validators.EmailValidator(), django.core.validators.RegexValidator(message='Enter a valid 10-digit mobile number.', regex='^[0-9]{10}$')])),
                ('new_password', models.CharField(max_length=25)),
                ('date_feild', models.DateField()),
                ('gender', models.CharField(max_length=10)),
            ],
        ),
    ]
