# Generated by Django 4.2 on 2023-11-12 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_rename_mobile_or_email_registrationpage_contactinput'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrationpage',
            name='contactinput',
            field=models.BigIntegerField(),
        ),
    ]
