# Generated by Django 4.2 on 2023-11-12 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_registrationpage_contactinput'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Registrationpage',
        ),
    ]
