# Generated by Django 4.2 on 2023-11-16 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_delete_registrationpage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Loginpage',
        ),
    ]
